// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/order/service/pkg/api"
	"github.com/order/service/pkg/api/handler"
	"github.com/order/service/pkg/config"
	"github.com/order/service/pkg/db"
	"github.com/order/service/pkg/repository"
	"github.com/order/service/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHttp, error) {
	gormDB, err := db.ConnectToDataBase(cfg)
	if err != nil {
		return nil, err
	}
	orderRepo := repository.NewOrderRepo(gormDB)
	orderUseCase := usecase.NewOrderUseCase(orderRepo)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	serverHttp := api.NewServerHttp(orderHandler)
	return serverHttp, nil
}
